### ISSUE TITLE
Possible to add this behind reverse-proxy?

### ISSUE THREAD

**Issue by polhaghverdian** [Place1/wg-access-server#102]
Hi,

If i would like to add this app behind an reverse-proxy with nginx. Is it possible? Any help will be appreciated.

**Comment by idelsink** [comment]
I'm running it behind traefik with a http router for the front end and a udp proxy for wg. So yes, it's possible

**Comment by Adorfer** [comment]
yes, it's possble to run the webinterface behing nginx als source-proxy. 
It's no probleme at all!

**Comment by polhaghverdian** [comment]
@Adorfer Could you provide an example?

**Comment by alexander-koval** [comment]
I've start that app on port 8080
Than I start nginx with configuration like this:
```
server {
    listen 80;
    listen [::]:80;
    server_name <example.domain.name>;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:8080;
    }
}
```
and it work's.
But unfortunately I can't start it over https.

**Comment by mrgreywater** [comment]
here is mine (wg-access-server running on 10.2.248.212:8000):

since you don't seem to be able to change the web root of wg-access-server, the rewriting rules are atrocious.
```
	location /wireguard {
		
		proxy_pass http://10.2.248.212:8000;
		proxy_redirect ~^/(.*) http://$http_host/wireguard/$1;
		proxy_set_header Host '10.2.248.212';
		proxy_set_header Referer 'http://10.2.248.212/signin';
		
		rewrite /wireguard(/.*|$) $1  break;
		
		sub_filter "href='/" "href='/wireguard/";
	    	sub_filter 'href="/' 'href="/wireguard/';
	    	sub_filter "href:'/" "href:'/wireguard/";
	    	sub_filter 'href:"/' 'href:"/wireguard/';
	    	sub_filter "src='/" "src='/wireguard/";
	    	sub_filter 'src="/' 'src="/wireguard/';
	    	sub_filter 'url(/' 'url(/wireguard/';
	    	sub_filter "'/api" "'/wireguard/api";
	    	sub_filter '"/api' '"/wireguard/api';
		sub_filter_once off;
		sub_filter_types *;
	}
```
