### ISSUE TITLE
Android can re-use the iOS QR Code

### ISSUE THREAD

**Issue by ariejan** [Place1/wg-access-server#11]
> TODO: I don't have an android phone :(

I can confirm that Wireguard on android can use the same QR code as iOS.

## Steps taken

 1. Install wg-access-server
 1. Add a new device, but use the iOS QR Code and instructions with the Wireguard Android app
 1. Have a working Wireguard connection

I don't have time to dive into React and make this (I think trivial change) myself; but it should be easy enough to add the same QR code and instructions to the Android tab. Just wanted to let you know I tested this - and it works.

**Comment by Place1** [comment]
Great! Thanks for this. I’ll update the ui when I next have time :)

**Comment by Place1** [comment]
@ariejan this is fixed in 0.0.9
