### ISSUE TITLE
\time="2021-03-07T12:02:20Z" level=fatal msg="missing admin password: please set via environment variable, flag or config file" file="main.go:202"

### ISSUE THREAD

**Issue by outbackdingo** [Place1/wg-access-server#114]
i tried 
helm upgrade --install vpn --repo https://place1.github.io/wg-access-server wg-access-server -f wireguard.yml --set "--admin-password=xxxxxxx"

but it fails with CrashLoopBackOff with logs showing

\time="2021-03-07T12:02:20Z" level=fatal msg="missing admin password: please set via environment variable, flag or config file" file="main.go:202"

**Comment by outbackdingo** [comment]
i think its time to update some documents, no mention of the admin username: admin password: 

https://place1.github.io/wg-access-server/deployment/3-kubernetes/

**Comment by sfxworks** [comment]
Still an issue but for anyone reading this I found it here https://github.com/Place1/wg-access-server/blob/master/deploy/helm/wg-access-server/values.yaml#L4-L7
