### ISSUE TITLE
how to set the public key?

### ISSUE THREAD

**Issue by diazzaid** [Place1/wg-access-server#139]
I need it for server backup purposes, so that from the user side there is no need to change the public key again key (duplicate server)

**Comment by DasSkelett** [comment]
The public key is always generated from the private key. It can not be specified separately.
To keep a static private key and thus a static public key, you need to set the private key in the config, pass it as argument or set the corresponding environment variable.

**Comment by diazzaid** [comment]
> The public key is always generated from the private key. It can not be specified separately.
> To keep a static private key and thus a static public key, you need to set the private key in the config, pass it as argument or set the corresponding environment variable.

ok thanks
