### ISSUE TITLE
Only able to access LAN

### ISSUE THREAD

**Issue by Adzter** [Place1/wg-access-server#16]
Setup the container using docker-compose up, no changes to the configuration. Then created a new device, selected iOS and scanned the QR code.

I can then connect and the web interface traffic stats start to go up. When trying to access any webpage, I get a connection time out. Connecting to any of my internal devices (ie. router webpage) seems to work no problem. I'm not sure if having my network on 172.16.x.x has caused some kind of conflict?

I'm not sure what logs I can post to help debug this. If you know of any information I can get that would be useful, i'll be happy to post it.

**Comment by Adzter** [comment]
Looks like this was a DNS issue, changing the DNS fixed this issue.

**Comment by Place1** [comment]
@Adzter glad you got it fixed. what did you need to change to solve your issue?

my goal is to make this the easiest VPN solution to run for enthusiasts so I want to make sure the defaults work out of the box :)
