### ISSUE TITLE
Fresh install on Kubernetes cant access services

### ISSUE THREAD

**Issue by iliaspoli** [Place1/wg-access-server#171]
Hi guys, I just installed the wg-access-server in my kubernetes cluster by using helm in or der to be able to access the private services via my workstation
I used the following command
`helm install wireguard -n vpn --repo https://place1.github.io/wg-access-server wg-access-server \ --set wireguard.config.privateKey=xxxxxxxxxxxxxxxxxxxxxxxxxxx \ --set config.adminPassword=xxxxxxxxxxxxxxxxxxx \ --set ingress.enabled=true \ --set ingress.hosts={vpn.xxxxxxxxx.com}`

however when I connect to the vpn I cannot access any of the internal services by pinging their cluster ips or fqdns nor am able to access external websites like google.com etc.
The services/ingresses themselves are working fine, it looks like a networking issue but it should be working no?
Am I missing a configuration or something?
Apologies but I am by no means a k8s or networking expert and cant find enough info to solve this.

**Comment by GoliathLabs** [comment]
@IliasP91 You might want to try our fork of this project, which is actively maintained and has implemented some improvements to the helm chard and several other features (https://github.com/freifunkMUC/wg-access-server)

**Comment by iliaspoli** [comment]
@GoliathLabs  hello, i have actually sorted this issue out it was an issue on my client with another vpn, however it is running extremely slow when connected and i dont know why, ill give your fork a go and if i experience the same ill raise an issue there to have a look. 
closing this one, thanks
