### ISSUE TITLE
Use email as the owner

### ISSUE THREAD

**Issue by KimchaC** [Place1/wg-access-server#21]
Hi,

First of all I want to thank you for this phenomenal project. You have done an amazing job.

I have a small feature request: When using OIDC (google), can you show the user's email as the owner instead of the token?

The reason is that it's impossible to actually tie the token to an actual user in case access needs to be revoked.

Thanks, Kim

**Comment by Place1** [comment]
Hey this is a great feature request. I'll add it to my todo list!
