### ISSUE TITLE
[docs] Missing gitlab auth guidelines

### ISSUE THREAD

**Issue by Sudokamikaze** [Place1/wg-access-server#23]
Hey, first of all, thank you for your project! Opening an issue as TODO doesn't have any points of gitlab auth guidelines/notes/documentation, such as:

- what type of permission should be granted
- callback URI(redirectURL)

**Comment by Sudokamikaze** [comment]
I've found an issue(which is closed rn), there is little information which might help me making PR

Should gitlab use `auth/callback` URI as well?

**Comment by Place1** [comment]
Hey, thanks for raising this. Gitlab auth requires only the OIDC permission. The callback uri can be any url that doesn't conflict with an existing wg-access-server url (i.e. not /); i recommend using `/auth/callback`.

I'll try to add these docs soon!

**Comment by Sudokamikaze** [comment]
> Hey, thanks for raising this. Gitlab auth requires only the OIDC permission. The callback uri can be any url that doesn't conflict with an existing wg-access-server url (i.e. not /); i recommend using `/auth/callback`.
> 
> I'll try to add these docs soon!

Yup, I've tried with `/auth/callback` and it works as intended.
Thank u, closing the issue
