### ISSUE TITLE
Small UI adjustments

### ISSUE THREAD

**Issue by KimchaC** [Place1/wg-access-server#28]
A few more super low priority things I have noticed...

### 1. Button order on add screen
When you add a new config on the download screen it says 

1. Install WireGuard for MacOS
2. Download your connection file
3. Add tunnel from file

But the buttons show:
- Download VPN Config
- Download wireguard

### 2. Linux screen without instructions
The linux screen just shows `1. hmmm todo` instead of the steps like the other OS

### 3. No app links for iOS and Android
Since iOS and Android show the QR code, I think you could just make the `WireGuard app` text in the instructions on the left a link to the app stores.

### 4. Customize OIDC button
The config OIDC section as a `name` variable, but it doesn't seem to be used anywhere. I think it would be great to replace the OIDC button text with that value.

**Comment by Place1** [comment]
All great suggestions. I'm going to wait or some more UI related things to stack up and i'll try to get them all done for a future 0.3.0 release
