### ISSUE TITLE
Can't find user folder because OpenID token is changing

### ISSUE THREAD

**Issue by vincentbitter** [Place1/wg-access-server#3]
Every time the docker container is restarted, users do receive a new token from the OpenID provider. Since this token is set as 'auth/subject' and therefore used as foldername, it is not possible to list the previously created profiles for a user.

Not sure how to fix it yet, but I would suggest setting the username or email instead of idToken.Subject as 'auth/subject': https://github.com/Place1/wg-access-server/blob/4c89f9ab1f8da6484df191f05b4c056661048fa7/internal/auth/dex.go#L130

**Comment by Place1** [comment]
@vincentbitter i've re-implemented the auth integrations. This is probably fixed now, give 0.0.9 another go. Checkout the README for config file changes.

**Comment by Place1** [comment]
_please reopen if there is still a problem :)_
