### ISSUE TITLE
Trailing slash required in STORAGE_DIRECTORY

### ISSUE THREAD

**Issue by vincentbitter** [Place1/wg-access-server#4]
When the environment variable STORAGE_DIRECTORY is set to `/data` and OpenId is used to login, listing the profiles does not work. New profiles are stored in /data/xxx/yyy.json, but it looks like listing is going wrong. It might looks for /dataxxx/*.json? 

https://github.com/Place1/wg-access-server/blob/4c89f9ab1f8da6484df191f05b4c056661048fa7/internal/storage/disk.go#L52

If the enviroment variable is set to `/data/`, everything works fine!

**Comment by Place1** [comment]
ahh, cheers for finding this one. i'll admit i haven't used the auth provider feature very much myself yet. i'd be happy to accept a PR fixing this and any other changes you'd like to see.
