### ISSUE TITLE
Ability to set externalHost and port from environment variables

### ISSUE THREAD

**Issue by pmontepagano** [Place1/wg-access-server#42]
It would be great if it were possible to set this two Wireguard configuration options from env vars:

- externalHost
- port

**Comment by Place1** [comment]
@pmontepagano thanks for raising this (sorry for being slow to respond).

I've opened #43 to address this and to cover all configuration more broadly.

**Comment by Place1** [comment]
Hey @pmontepagano i know it's been a really long time 😅 but this is now implemented. You can configure these options using `WG_EXTERNAL_HOST` and `WG_PORT`.

https://place1.github.io/wg-access-server/2-configuration/
