### ISSUE TITLE
Improve client connection status display

### ISSUE THREAD

**Issue by arctica** [Place1/wg-access-server#48]
The web ui will show clients as disconnected if the last handshake was more than 1 minute ago.

As far as I can tell wireguard will only establish a new handshake if the current one is more than 120s ago and only when data is sent. If no data is transferred no new handshake will be established.

This results in clients being incorrectly shown as disconnected even if they are still there but the last handshake has been more than 1 minute ago.

I suggest increasing the duration to 3 minutes.

Maybe a config option that adds a PersistentKeepalive entry for the client configs could be of use as well.

**Comment by Place1** [comment]
Yeah 3m makes much more sense. I'll make this change.

> Maybe a config option that adds a PersistentKeepalive entry for the client configs could be of use as well.

I agree.
