### ISSUE TITLE
404 error on page refresh for /admin/all-devices

### ISSUE THREAD

**Issue by arctica** [Place1/wg-access-server#56]
When logged in as admin and viewing /admin/all-devices, a page refresh will result in a 404 error.

PS: the "auth provider" on the all-devices page seems to be empty for users who used Gitlab auth.

**Comment by Place1** [comment]
Yep, this is a long standing bug that I haven't got around to fixing. I'll try and get a fix for this soon

**Comment by Place1** [comment]
this is now fixed :D
