### ISSUE TITLE
Add search domain option to dns config

### ISSUE THREAD

**Issue by analogue** [Place1/wg-access-server#62]
It would be nice to have the equivalent of the openvpn config for search domains:
```
push "dhcp-option DOMAIN blah"
```
Maybe this is a good starting point: https://lists.zx2c4.com/pipermail/wireguard/2019-September/004579.html

Or just pick it up from /etc/resolv.conf (seems this is where you pick up the default dns server to forward to)?
```
nameserver 192.168.1.1
search blah
```

**Comment by Place1** [comment]
Hey @analogue i'm not too sure what your asking here. Is this related to configuring dns search domains on vpn clients?

**Comment by analogue** [comment]
So let's say my private home network's domain name is `.foo` and the `/etc/resolv.conf` has a `search foo` so that this domain is searched when not specified.  The net result is that I can access a host `server1.foo` as either `server1.foo` or plain old `server1`.

This behavior is replicated in openvpn clients by the openvpn server pushing this config request to the client via `push "dhcp-option DOMAIN blah"`.  

That means I can be lazy and continue using `server1` on my openvpn client and still have it resolve to `server1.foo` automagically.

This request revolves around replicating this behavior on a wireguard client.  I'm forced to always use `server1.foo` instead of my lazy muscle memory habit of doing `server1`.   This is not such a big deal on clients with a physical keyboard, but saves keystrokes on mobile clients and is somewhat of a creature comfort.  

I'm suggesting that wg-access-server pick up `search foo` from `/etc/resolv.conf` on the server and do the same as openvpn by pushing that config option (assuming this is possbile) to the wireguard client.   Does that make sense?

**Comment by Place1** [comment]
I'm not too sure how this could be supported in wg-access-server. Your client's receive a standard wireguard config file and it's up to the official applications to configure the client's DNS settings. There's not _push_ feature here.

Similarly, wireguard client's only support configuration of an upstream DNS server.

We could probably replicate the `search` feature within wg-access-server's DNS proxy; but i'd prefer not to add bespoke features to the DNS proxy in this case.

I think this is out of scope. Apologies.

**Comment by tomalexander** [comment]
On linux I can specify a domain name on the `DNS` line in my wg-quick config file and it gets added as a search domain. For example:
```
DNS = 10.44.0.1, default.svc.cluster.local
```
becomes this in my `resolv.conf`:
```
search default.svc.cluster.local
nameserver 10.44.0.1
```

So I think this feature would just need to either parse `/etc/resolv.conf` and append to the `DNS` line or we could just support adding a list of additional `DNS` line entries from the config similar to how `allowedIPs` is already handled.
