### ISSUE TITLE
Add support for PostUp

### ISSUE THREAD

**Issue by analogue** [Place1/wg-access-server#68]
I'd like to add some iptables rules after the wg0 interface for the wg-access-server comes up.  Supporting a `PostUp` config option similiar to [wg-quick](https://manpages.debian.org/unstable/wireguard-tools/wg-quick.8.en.html) seems like the most straight forward way to achieve that.

**Comment by Place1** [comment]
I think this will be out of scope for now. My intent is to build an out of the box experience that just works for people who don't necessarily know how a vpn, iptables, networking etc all work.

I can see the value in having the ability to configure your own IP tables rules but for now I would recommend implementing this using other means. Apologies.
