### ISSUE TITLE
sqlite Error 

### ISSUE THREAD

**Issue by BCNelson** [Place1/wg-access-server#74]
failed to connect/open storage backend: failed to connect to sqlite3: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub" file="main.go:77"

**Comment by BCNelson** [comment]
I think that you need to update your docker file. to remove the deprecation warning and make sqlite work

**Comment by Place1** [comment]
Yep, i've actually been working on that today 👍 

Master is just building now; hopefully that'll solve your issue.
