### ISSUE TITLE
docker-compose.yml version 3.7 incompatible with Debian 10.6

### ISSUE THREAD

**Issue by mlawren** [Place1/wg-access-server#76]
The current stable version of Debian provides `docker-compose` version 1.21.0, which complains with:

    ERROR: Version in "./docker-compose.yml" is unsupported

Local docker man pages don't give me any indication of the .yml format and version requirements. Is wg-accerss-server using modern docker compose yml file features? Could it possibly be re-worked to support older versions?

**Comment by Place1** [comment]
Yeah I'd expect it to work if you lower the version. Give it try with any of the following versions in the compose file and let me know which works so I can update the README

https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

**Comment by mlawren** [comment]
Setting it to 3.6 eliminates that particular error. It appears the use of "volumes" would make the minimum format value 3.0 which also appears to work.

Rather than changing just the README, wouldn't specifying the lowest acceptable format in docker-compose.yml itself "just work" for the largest group of users?
