### ISSUE TITLE
Broken CHANGELOG link to storage migration documentation

### ISSUE THREAD

**Issue by mlawren** [Place1/wg-access-server#77]
Changelog entry for version v0.3.0 has a link[1] that returns a 404.

[1] https://place1.github.io/wg-access-server/storage/#migration-between-backends

**Comment by Place1** [comment]
Thanks! I've updated it.

**Comment by mlawren** [comment]
Another one: the (Quick Links) "Configuration Overview" link on the main documentation page is also broken.
