### ISSUE TITLE
Option to disable authentication

### ISSUE THREAD

**Issue by rb28z2** [Place1/wg-access-server#87]
I currently run wg-access-server in an environment that already provides basic authentication. I'd like to keep using that and completely disable any authentication wg-access-server requires.

As it stands, I'm unable to use my existing authentication as the two basic methods seem to conflict.

**Comment by Place1** [comment]
We used to support no-auth but i've removed it to avoid having to maintain the feature.

I recommend just using the basic auth built into wg-access-server, it's pretty easy to configure.
