### ISSUE TITLE
Fresh install, client has no access to internet, restart docker container and it works

### ISSUE THREAD

**Issue by Ddataa** [Place1/wg-access-server#93]
Hi there,

Thanks for that great project.

I am trying to use it but after installing when I try to add users they can connect correctly but get no access to internet.
After restarting the docker container it does works, but I can't restart the docker at each client creation...

Is is a normal feature or I am missing some bits of configuration or anything else..?

**Comment by Place1** [comment]
Hey, this does sound like a bug.

Could I ask if there are any logs/config you can attach to help me debug
this? You can set the log level to “debug” to get some more verbose output.

**Comment by Ddataa** [comment]
The log show nothing on the server side...even at debug level

time="2020-12-14T11:28:38Z" level=info msg="starting wireguard server on 0.0.0.0:51820" file="main.go:86"
time="2020-12-14T11:28:38Z" level=debug msg="set interface up" file="iface_linux.go:25"
time="2020-12-14T11:28:38Z" level=info msg="wireguard VPN network is 10.44.0.0/24" file="main.go:100"
time="2020-12-14T11:28:38Z" level=info msg="starting dns server on 0.0.0.0:53 with upstreams: 94.140.14.14, 94.140.15.15, 2a10:50c0::ad1:ff, 2a10:50c0::ad2:ff" file="server.go:33"
time="2020-12-14T11:28:38Z" level=info msg="storing data in SQL backend sqlite3" file="contracts.go:71"
time="2020-12-14T11:28:38Z" level=debug msg="SELECT * FROM \"devices\"  " file="sql.go:32" module=gorm rows=2 src_ref="/code/internal/storage/sql.go:155" type=sql values="[]"
time="2020-12-14T11:28:38Z" level=debug msg="found 2 device(s)" file="sql.go:158"
time="2020-12-14T11:28:38Z" level=info msg="serving website from ./website/build" file="website_router.go:37"
time="2020-12-14T11:28:38Z" level=info msg="web ui listening on 0.0.0.0:8000" file="main.go:181"
time="2020-12-14T11:28:38Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:29:08Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:29:30Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=Info grpc.service=proto.Server grpc.start_time="2020-12-14T11:29:30Z" grpc.time_ms=0.927 span.kind=server system=grpc trace.id=bc55909b-9691-42e9-bc5c-ec3d78bb254d
time="2020-12-14T11:29:30Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=2 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxx]"
time="2020-12-14T11:29:30Z" level=debug msg="found 2 device(s)" file="sql.go:158"
time="2020-12-14T11:29:30Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:29:30Z" grpc.time_ms=0.906 span.kind=server system=grpc trace.id=18c6c579-b337-48f9-87a0-49bb1fdcbcf9
time="2020-12-14T11:29:34Z" level=debug msg="SELECT * FROM \"devices\"  " file="sql.go:32" module=gorm rows=2 src_ref="/code/internal/storage/sql.go:155" type=sql values="[]"
time="2020-12-14T11:29:34Z" level=debug msg="found 2 device(s)" file="sql.go:158"
time="2020-12-14T11:29:34Z" level=debug msg="saving device xxxxxx/TestPhone" file="sql.go:142"
time="2020-12-14T11:29:34Z" level=debug msg="UPDATE \"devices\" SET \"owner_name\" = ?, \"owner_email\" = ?, \"owner_provider\" = ?, \"public_key\" = ?, \"address\" = ?, \"created_at\" = ?, \"last_handshake_time\" = ?, \"receive_bytes\" = ?, \"transmit_bytes\" = ?, \"endpoint\" = ?  WHERE \"devices\".\"owner\" = ? AND \"devices\".\"name\" = ?" file="sql.go:32" module=gorm rows=0 src_ref="/code/internal/storage/sql.go:143" type=sql values="[xxxx  basic xxxxxxxxxx= 10.44.0.3/32 2020-12-14 11:29:34.220425344 +0000 UTC m=+55.808495576 <nil> 0 0  xxxxxx TestPhone]"
time="2020-12-14T11:29:34Z" level=debug msg="SELECT * FROM \"devices\"  WHERE \"devices\".\"owner\" = ? AND \"devices\".\"name\" = ? ORDER BY \"devices\".\"owner\" ASC LIMIT 1" file="sql.go:32" module=gorm rows=0 src_ref="/code/internal/storage/sql.go:143" type=sql values="[xxxxxx TestPhone]"
time="2020-12-14T11:29:34Z" level=debug msg="INSERT INTO \"devices\" (\"owner\",\"owner_name\",\"owner_email\",\"owner_provider\",\"name\",\"public_key\",\"address\",\"created_at\",\"last_handshake_time\",\"receive_bytes\",\"transmit_bytes\",\"endpoint\") VALUES (?,?,?,?,?,?,?,?,?,?,?,?)" file="sql.go:32" module=gorm rows=1 src_ref="/code/internal/storage/sql.go:143" type=sql values="[xxxxx xxxxx  basic TestPhone xxxxxxxxxxx 10.44.0.3/32 2020-12-14 11:29:34.220425344 +0000 UTC m=+55.808495576 <nil> 0 0 ]"
time="2020-12-14T11:29:34Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=AddDevice grpc.service=proto.Devices grpc.start_time="2020-12-14T11:29:34Z" grpc.time_ms=8.648 span.kind=server system=grpc trace.id=0fd0a213-af6a-4f41-9fab-ba8aa9546e54
time="2020-12-14T11:29:34Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=3 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxx]"
time="2020-12-14T11:29:34Z" level=debug msg="found 3 device(s)" file="sql.go:158"
time="2020-12-14T11:29:34Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:29:34Z" grpc.time_ms=1.133 span.kind=server system=grpc trace.id=6b0cb553-9b5e-4c94-bbff-15f1e5b576e9
time="2020-12-14T11:29:38Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:30:01Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=3 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxxxx]"
time="2020-12-14T11:30:01Z" level=debug msg="found 3 device(s)" file="sql.go:158"
time="2020-12-14T11:30:01Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:30:01Z" grpc.time_ms=0.915 span.kind=server system=grpc trace.id=0909745f-8ec8-4711-bec9-51144e0e00d1
time="2020-12-14T11:30:08Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:30:32Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=3 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxxxxx]"
time="2020-12-14T11:30:32Z" level=debug msg="found 3 device(s)" file="sql.go:158"
time="2020-12-14T11:30:32Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:30:32Z" grpc.time_ms=1.17 span.kind=server system=grpc trace.id=6b296088-1a81-42fe-83af-d41227406299
time="2020-12-14T11:30:38Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:31:03Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=3 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxxxxx]"
time="2020-12-14T11:31:03Z" level=debug msg="found 3 device(s)" file="sql.go:158"
time="2020-12-14T11:31:03Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:31:03Z" grpc.time_ms=0.902 span.kind=server system=grpc trace.id=06c181ba-b82f-46a3-ab47-e53a8f3023c7
time="2020-12-14T11:31:08Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:31:34Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=3 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxxxx]"
time="2020-12-14T11:31:34Z" level=debug msg="found 3 device(s)" file="sql.go:158"
time="2020-12-14T11:31:34Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:31:34Z" grpc.time_ms=0.94 span.kind=server system=grpc trace.id=2e3829c1-8822-4b9b-92af-d34f86f56a29
time="2020-12-14T11:31:38Z" level=debug msg="metadata sync executing" file="metadata.go:18"
time="2020-12-14T11:32:05Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = ?)" file="sql.go:32" module=gorm rows=3 src_ref="/code/internal/storage/sql.go:153" type=sql values="[xxxxxxxx]"
time="2020-12-14T11:32:05Z" level=debug msg="found 3 device(s)" file="sql.go:158"
time="2020-12-14T11:32:05Z" level=info msg="finished unary call with code OK" file="server_interceptors.go:95" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2020-12-14T11:32:05Z" grpc.time_ms=0.89 span.kind=server system=grpc trace.id=9bce41ed-de69-46d8-9ba9-9988c423e12b
time="2020-12-14T11:32:08Z" level=debug msg="metadata sync executing" file="metadata.go:18"



on the client side I just get an net::ERR_NAME_NOT_RESOLVED in my web browser

could it be linked to issue 91 ?
https://github.com/Place1/wg-access-server/issues/91

**Comment by Place1** [comment]
@Ddataa thanks for the additional information. i've released an update that fixes the issue. please give v0.4.5 a try and hopefully you'll be set!

**Comment by Ddataa** [comment]
Yes it works.
Would you please give details about what was the error and the correction you made ?

Thanks
