### ISSUE TITLE
Bandwidth limit for upload/download

### ISSUE THREAD

**Issue by frenzi2012** [Place1/wg-access-server#96]
Hi, bandwidth is limited for upload to 0.5Mb/s and download 20Mb/s per client. How can i change this values? i using helm chart. i want to upload to 5Mb/s. runing in aws eks

**Comment by Place1** [comment]
wg-access-server doesn’t implement any bandwidth control features.

Your limit must be somewhere else in the stack.

**Comment by frenzi2012** [comment]
Thanks for asking,
Any way to set MTU in server side? I searching in web and maybe is that.

**Comment by Place1** [comment]
You can use the `ip` command on linux to modify the MTU size of a network interface.

From a quick google the command would be:

`ip link set <iface> mtu <value>`

You could try running this inside the wg-access-server container: e.g. `ip link set wg0 mtu 1500`
