### ISSUE TITLE
CHANGELOG.md should include a date

### ISSUE THREAD

**Issue by FrankBlackMG** [Place1/wg-access-server#97]
Minor issue: According to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) one of their guiding principals is to incude a date for each release.

E.g. ## [1.0.0] - 2021-01-12

**Comment by Place1** [comment]
Yeah ok, i'll start doing this. 

just in case you need dates for existing releases you can find them here: https://github.com/Place1/wg-access-server/releases
